INFO     backend.layers.business.business:business.py:598 {'message': 'ingesting dataset', 'collection_version_id': 6c6d87f9-b5b0-4457-9c8a-842e81adf385, 'manifest': IngestionManifest(anndata=HttpUrl('http://fake.url/'), atac_fragment=None), 'current_dataset_version_id': None}
INFO     backend.layers.business.business:business.py:598 {'message': 'ingesting dataset', 'collection_version_id': 6c6d87f9-b5b0-4457-9c8a-842e81adf385, 'manifest': IngestionManifest(anndata=HttpUrl('http://fake.url/'), atac_fragment=None), 'current_dataset_version_id': a30db229-bf77-45ac-bf4f-619bd9242b66}
INFO     processing:dataset_metadata_update.py:273 Main: No raw h5ad update required
INFO     processing:process_logic.py:49 Updating processing status
INFO     processing:process_logic.py:49 Updating processing status
INFO     processing:logger.py:26 Start create_artifact
INFO     processing:process_logic.py:49 Updating processing status
INFO     processing:process_logic.py:100 Uploaded [329cb9f0-1d55-4bcb-9685-487308f3cb86/raw.h5ad] to s3://artifact_bucket/329cb9f0-1d55-4bcb-9685-487308f3cb86/raw.h5ad
INFO     processing:process_logic.py:102 Updated database with raw_h5ad.
INFO     processing:process_logic.py:49 Updating processing status
INFO     processing:logger.py:28 Complete create_artifact
INFO     processing:process_logic.py:49 Updating processing status
INFO     processing:dataset_metadata_update.py:278 Main: Starting thread for h5ad update
INFO     processing:process_logic.py:49 Updating processing status
ERROR    processing:dataset_metadata_update.py:318 Cannot find cxg artifact uri for a30db229-bf77-45ac-bf4f-619bd9242b66.
INFO     processing:process_logic.py:49 Updating processing status
INFO     processing:process_logic.py:49 Updating processing status