INFO     backend.layers.business.business:business.py:511 {'message': 'ingesting dataset', 'collection_version_id': e4e70e30-bdc8-494e-8e70-1c812aaa83ca, 'url': 'http://fake.url', 'current_dataset_version_id': None}
INFO     backend.layers.business.business:business.py:511 {'message': 'ingesting dataset', 'collection_version_id': e4e70e30-bdc8-494e-8e70-1c812aaa83ca, 'url': None, 'current_dataset_version_id': 46017de6-a9b2-4cbc-b72e-4c38518b7380}
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:logger.py:26 Start create_artifact
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:process_logic.py:91 Uploaded [540fb712-1f8a-428f-a518-8110c0d0f75c/raw.h5ad] to s3://artifact_bucket/540fb712-1f8a-428f-a518-8110c0d0f75c/raw.h5ad
INFO     processing:process_logic.py:93 Updated database with raw_h5ad.
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:logger.py:28 Complete create_artifact
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:dataset_metadata_update.py:244 Main: Starting thread for h5ad update
INFO     processing:dataset_metadata_update.py:264 Main: Starting thread for rds update
ERROR    processing:dataset_metadata_update.py:302 Cannot find cxg artifact uri for 46017de6-a9b2-4cbc-b72e-4c38518b7380.
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:process_logic.py:45 Updating processing status