{"levelname": "ERROR", "asctime": "2024-02-29T22:09:06.029Z", "name": "processing", "message": "Unable to publish collection version.", "lineno": 69, "pathname": "/single-cell-data-portal/backend/layers/processing/publish_revisions.py", "collection_id": "0ed329b9-f2a4-4f05-81b9-b7fe127350c7", "collection_version_id": "dc446f9c-e871-4c9d-b4f0-a1057de657c3", "errors": ["error message"]}
