INFO     backend.layers.business.business:business.py:534 {'message': 'ingesting dataset', 'collection_version_id': aa938d7c-7a57-47f3-a6d9-1cf451a2c2f0, 'url': 'http://fake.url', 'current_dataset_version_id': None}
INFO     backend.layers.business.business:business.py:534 {'message': 'ingesting dataset', 'collection_version_id': aa938d7c-7a57-47f3-a6d9-1cf451a2c2f0, 'url': None, 'current_dataset_version_id': 08e853d0-6d51-4bd0-bc81-23a9d6882b6e}
INFO     processing:dataset_metadata_update.py:333 Main: No raw h5ad update required
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:logger.py:26 Start create_artifact
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:process_logic.py:91 Uploaded [5cbd6119-803a-4798-a6e9-1c4c8481c47d/raw.h5ad] to s3://artifact_bucket/5cbd6119-803a-4798-a6e9-1c4c8481c47d/raw.h5ad
INFO     processing:process_logic.py:93 Updated database with raw_h5ad.
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:logger.py:28 Complete create_artifact
INFO     processing:process_logic.py:45 Updating processing status
ERROR    processing:dataset_metadata_update.py:353 Cannot find labeled H5AD artifact uri for 08e853d0-6d51-4bd0-bc81-23a9d6882b6e.
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:dataset_metadata_update.py:357 Main: Starting thread for rds update
INFO     processing:dataset_metadata_update.py:380 Main: Starting thread for cxg update
INFO     processing:process_logic.py:45 Updating processing status