INFO     backend.layers.business.business:business.py:517 {'message': 'ingesting dataset', 'collection_version_id': 8b812f81-5196-4490-a914-57c2c60d6073, 'url': 'http://fake.url', 'current_dataset_version_id': None}
INFO     backend.layers.business.business:business.py:517 {'message': 'ingesting dataset', 'collection_version_id': 8b812f81-5196-4490-a914-57c2c60d6073, 'url': None, 'current_dataset_version_id': 68005f3e-4825-456a-8232-023610ac8b87}
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:logger.py:26 Start create_artifact
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:process_logic.py:91 Uploaded [de9d1765-4a40-4c66-9798-09de4f9e098a/raw.h5ad] to s3://artifact_bucket/de9d1765-4a40-4c66-9798-09de4f9e098a/raw.h5ad
INFO     processing:process_logic.py:93 Updated database with raw_h5ad.
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:logger.py:28 Complete create_artifact
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:dataset_metadata_update.py:245 Main: Starting thread for h5ad update
INFO     processing:dataset_metadata_update.py:265 Main: Starting thread for rds update
ERROR    processing:dataset_metadata_update.py:303 Cannot find cxg artifact uri for 68005f3e-4825-456a-8232-023610ac8b87.
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:process_logic.py:45 Updating processing status