INFO     backend.layers.business.business:business.py:517 {'message': 'ingesting dataset', 'collection_version_id': 8b4d919a-27c3-48e7-b1ff-800400333d11, 'url': 'http://fake.url', 'current_dataset_version_id': None}
INFO     backend.layers.business.business:business.py:517 {'message': 'ingesting dataset', 'collection_version_id': 8b4d919a-27c3-48e7-b1ff-800400333d11, 'url': None, 'current_dataset_version_id': 5a4578cf-309a-4124-99fd-45ecc23d4c24}
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:logger.py:26 Start create_artifact
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:process_logic.py:91 Uploaded [8dbc1f67-527b-4b99-b227-db68fed9f93b/raw.h5ad] to s3://artifact_bucket/8dbc1f67-527b-4b99-b227-db68fed9f93b/raw.h5ad
INFO     processing:process_logic.py:93 Updated database with raw_h5ad.
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:logger.py:28 Complete create_artifact
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:dataset_metadata_update.py:245 Main: Starting thread for h5ad update
INFO     processing:dataset_metadata_update.py:265 Main: Starting thread for rds update
ERROR    processing:dataset_metadata_update.py:303 Cannot find cxg artifact uri for 5a4578cf-309a-4124-99fd-45ecc23d4c24.
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:process_logic.py:45 Updating processing status