INFO     backend.layers.business.business:business.py:511 {'message': 'ingesting dataset', 'collection_version_id': afef877a-74f0-421d-bcc3-15e29c9d3eff, 'url': 'http://fake.url', 'current_dataset_version_id': None}
INFO     backend.layers.business.business:business.py:511 {'message': 'ingesting dataset', 'collection_version_id': afef877a-74f0-421d-bcc3-15e29c9d3eff, 'url': None, 'current_dataset_version_id': 54f46883-5aa3-485d-960e-8830a9596c1d}
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:logger.py:26 Start create_artifact
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:process_logic.py:91 Uploaded [500387d0-d2a1-4a9c-8051-2fb978cb68c3/raw.h5ad] to s3://artifact_bucket/500387d0-d2a1-4a9c-8051-2fb978cb68c3/raw.h5ad
INFO     processing:process_logic.py:93 Updated database with raw_h5ad.
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:logger.py:28 Complete create_artifact
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:dataset_metadata_update.py:244 Main: Starting thread for h5ad update
ERROR    processing:dataset_metadata_update.py:281 Cannot find RDS artifact uri for 54f46883-5aa3-485d-960e-8830a9596c1d, and Conversion Status is not SKIPPED.
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:dataset_metadata_update.py:287 Main: Starting thread for cxg update
INFO     processing:process_logic.py:45 Updating processing status