INFO     backend.layers.business.business:business.py:553 {'message': 'ingesting dataset', 'collection_version_id': 8536b18c-c014-4f37-b2b6-695e6b95f0f4, 'url': 'http://fake.url', 'current_dataset_version_id': None}
INFO     backend.layers.business.business:business.py:553 {'message': 'ingesting dataset', 'collection_version_id': 8536b18c-c014-4f37-b2b6-695e6b95f0f4, 'url': None, 'current_dataset_version_id': 816a2ffe-4337-4414-9c06-a03236daad72}
INFO     processing:dataset_metadata_update.py:333 Main: No raw h5ad update required
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:logger.py:26 Start create_artifact
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:process_logic.py:91 Uploaded [6f765f37-2981-4a24-aca2-47e3dcb03172/raw.h5ad] to s3://artifact_bucket/6f765f37-2981-4a24-aca2-47e3dcb03172/raw.h5ad
INFO     processing:process_logic.py:93 Updated database with raw_h5ad.
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:logger.py:28 Complete create_artifact
INFO     processing:process_logic.py:45 Updating processing status
ERROR    processing:dataset_metadata_update.py:353 Cannot find labeled H5AD artifact uri for 816a2ffe-4337-4414-9c06-a03236daad72.
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:dataset_metadata_update.py:357 Main: Starting thread for rds update
INFO     processing:dataset_metadata_update.py:380 Main: Starting thread for cxg update
INFO     processing:process_logic.py:45 Updating processing status