INFO     backend.layers.business.business:business.py:517 {'message': 'ingesting dataset', 'collection_version_id': 65168c7c-0dd8-4cc0-a7dc-3ebc0e0395f5, 'url': 'http://fake.url', 'current_dataset_version_id': None}
INFO     backend.layers.business.business:business.py:517 {'message': 'ingesting dataset', 'collection_version_id': 65168c7c-0dd8-4cc0-a7dc-3ebc0e0395f5, 'url': None, 'current_dataset_version_id': 394c5295-51e8-4b2c-853a-7fc2ad93e468}
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:logger.py:26 Start create_artifact
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:process_logic.py:91 Uploaded [c2c6a914-0573-4e63-992e-819bf5acd5f4/raw.h5ad] to s3://artifact_bucket/c2c6a914-0573-4e63-992e-819bf5acd5f4/raw.h5ad
INFO     processing:process_logic.py:93 Updated database with raw_h5ad.
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:logger.py:28 Complete create_artifact
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:dataset_metadata_update.py:245 Main: Starting thread for h5ad update
ERROR    processing:dataset_metadata_update.py:282 Cannot find RDS artifact uri for 394c5295-51e8-4b2c-853a-7fc2ad93e468, and Conversion Status is not SKIPPED.
INFO     processing:process_logic.py:45 Updating processing status
INFO     processing:dataset_metadata_update.py:288 Main: Starting thread for cxg update
INFO     processing:process_logic.py:45 Updating processing status